#ifndef _OCLS_REGISTRKEY_EXPORT_H_
#define _OCLS_REGISTRKEY_EXPORT_H_
#include <osal/Osal.h>
#if defined(MAKINGDLL_REGISTRYKEY)
#define OCLS_REGISTRYKEY_API OSALEXPORT
#elif defined(USINGDLL_REGISTRYKEY)
#define OCLS_REGISTRYKEY_API OSALIMPORT
#else
#define OCLS_REGISTRYKEY_API
#endif
#endif